### ISSUE TITLE
Timeouts after migration from legacy package

### ISSUE THREAD

**Issue by drobnikj** [logdna/logger-node#15]
We migrated LogDNA npm package to this one from deprecated https://www.npmjs.com/package/logdna.

After migration, we started getting timeout errors from sending log.
```
Error: An error occured while sending logs to the cloud.
    at /app/node_modules/@logdna/logger/lib/logger.js:707:25
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
    at /app/node_modules/@logdna/logger/lib/logger.js:716:18
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  meta: {
    actual: 'timeout of 5000ms exceeded',
    code: 'ECONNABORTED',
    firstLine: '{"time":"2020-09-10T10:13:41.524Z","level":"SOFT_FAIL","msg":"Page not found"}',
    lastLine: null,
    retrying: true,
    attempts: 1
  }
}
```

I checked the previous legacy package and there was timeout [set to 180s](https://github.com/logdna/nodejs#timeout) by default. In this package there is just 5s, I guess this can an issue. Setting the same timeout can help other users to avoid these types of error.

**Comment by darinspivey** [comment]
Thanks @drobnikj for reporting your issue.  Perhaps 5 seconds is too short, but to me, something like 180 is too much.  There's retry logic for this type of error after all.  I think we can probably increase it to something like 30 seconds, but I'd consider anything longer to be abnormal and we should let the retry logic kick in.

In the meantime, feel free to pass your own `timeout` value to the constructor to lengthen the time until we get a patch released for this.
