### ISSUE TITLE
Eslint as peer dependency

### ISSUE THREAD

**Issue by bailey-byb** [logdna/logger-node#18]
Is there a reason why `eslint` is a peer dependency and not just a dev dependency?

I keep getting warnings for prod installs like below:

```
warning "@logdna/logger@1.3.1" has incorrect peer dependency "eslint@>= 6".
warning "logdna-winston > logdna@3.5.1" has incorrect peer dependency "eslint@>= 6".
```

**Comment by darinspivey** [comment]
No, this can be changed.  Thanks for reporting.
