### ISSUE TITLE
CORS issue with client-side usage (header ‘user-agent’ is not allowed)

### ISSUE THREAD

**Issue by pauloramires** [logdna/logger-node#21]
Hi,
I'm trying to use this library on a client-side project. I've followed the [Client Side](https://github.com/logdna/logger-node#client-side) guide and white-listed my domain, however, I'm getting the following CORS error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://logs.logdna.com/logs/ingest?now=xxxxxxxxxx&hostname=xxx.xxx.xxx&mac=&ip=&tags=. (Reason: header ‘user-agent’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).

The user agent included in the request headers is @logdna/logger/1.3.2.

Is there something I'm missing?

Thanks a lot

**Comment by darinspivey** [comment]
Hi, thanks for notifying us.  A fix will be up shortly.

**Comment by darinspivey** [comment]
We will get this fix into the next release cycle. I'm reopening this issue until that is complete. Stay tuned. Thanks.

**Comment by darinspivey** [comment]
The server-side fix for this has been deployed.  Please check again to see if it works for you now.  Thanks!

**Comment by pauloramires** [comment]
Hi Darin,
I can confirm it is working now.
Thanks a lot!
