### ISSUE TITLE
Allow to pass `ip` and `tags` into `log()` method

### ISSUE THREAD

**Issue by gbiryukov** [logdna/logger-node#3]
We write our node server access log with LogDNA. For each request to this http server, we trace `ip` address of the remote client, URL, status code and so on. 
This forces us to create new logger for each request because `ip` address is bound to the instance. All these instances are hard to manage and inefficient. Ability to specify `ip` at `log()` call would allow to use single instance in cases like this.

**Comment by darinspivey** [comment]
@gbiryukov, our [new node client](https://www.npmjs.com/package/@logdna/logger) was released yesterday.  We'd recommend upgrading to the new version, and shortly we can begin a minor release to add this requested feature!

**Comment by darinspivey** [comment]
A quick update on this feature request.  It's not going to be as simple to add as originally thought because the `ip` (and tags) is added at the request level, and each request contains multiple lines.  We can get it added, but it will require changes at the ingestion process.  Stand by, we won't forget about you!

**Comment by gbiryukov** [comment]
If my request does not fit into logger architecture we can move client IP into meta. I am curious about what would be the impact if we will do it?
we capture IP only for audit purposes and does not have any functionality on top of it.

**Comment by darinspivey** [comment]
> If my request does not fit into logger architecture we can move client IP into meta. I am curious about what would be the impact if we will do it?

Yes, that should work.  You'll want to set `indexMeta: true` so that the ip field (whatever you call it) is searchable.  Feel free to try this and report back if it's sufficient for you.  Thanks!
