### ISSUE TITLE
How to pass namespace line identifier

### ISSUE THREAD

**Issue by vladimir-krasulya2** [logdna/logger-node#51]
Hi 👋 
I'm trying to setup logging for aws lambda function and struggling to find a way how to set `namespace` , I've tried `meta: { namespace: 'abc' }` , but it's not working the same way as on k8 client.

**Comment by jorgebay** [comment]
Hi!
`namespace` is a reserved property for Kubernetes logs.

You could use `tags`, `app` or `env` to group related applications. Those can be set in both the k8s agent and in the node.js logger on any environment.

**Comment by jorgebay** [comment]
@vladimir-krasulya2 let us know if we can close this ticket.
