### ISSUE TITLE
allow user to disable log level validation 

### ISSUE THREAD

**Issue by emelski** [logdna/logger-node#65]
Currently, `logger-node` requires that the log level specified for a log message belongs to a pre-defined set of known log levels.  In my use case I'm aggregating logs from several sources, so the log levels are not known in advance.  Since `logger-node` passes the log level to LogDNA servers explicitly (that is, the level is specified in the JSON payload as `level: 'THE_LEVEL'`), LogDNA does not actually require that the log level belong to a predefined set -- this requirement appears to be imposed only by `logger-node`.  It would be nice if this additional constraint could be disabled.

**Comment by zhfahan77** [comment]
facing the same issue

**Comment by darinspivey** [comment]
Thanks for the ping, @zhfahan77.  We have not forgotten this and may even post some questions here to solicit feedback/opinions.

**Comment by emelski** [comment]
@zhfahan77 can you provide some more detail about your use case?

**Comment by darinspivey** [comment]
@emelski @zhfahan77 have we lost traction on this issue?  It's pretty old and should be closed out if it's not going to be fleshed out.

**Comment by emelski** [comment]
I no longer need this functionality so I'm happy to close it.
